[package]
name = "mandel_tut_rust"
version = "0.1.0"
authors = ["g_martins"]
edition = "2018"

[dependencies]
image = "^0.22.0"
num-complex = "^0.1.12"

[[bin]]
name = "mandel_tut_rust"
path = "main.rs"
